# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  version-bump:
    desc: Bump version and push tags
    cmds:
      - bumpversion patch
      - git push --tags
  pre-commit:
    desc: Run pre-commit hooks
    cmds:
      - composer validate --strict
